# Generated by Django 5.1.7 on 2025-03-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField()),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('programming', 'Programming'), ('web_dev', 'Web Development'), ('ai_ml', 'Artificial Intelligence & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('software', 'Software Engineering'), ('business', 'Business & Startups'), ('data_science', 'Data Science'), ('finance', 'Finance & Investment'), ('design', 'UI/UX & Product Design')], default='tech', max_length=50)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('ai_ml', 'AI & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('data_science', 'Data Science'), ('game_dev', 'Game Development'), ('cloud', 'Cloud Computing'), ('devops', 'DevOps & Automation'), ('software', 'Software Engineering'), ('other', 'Other')], default='web_dev', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.technology')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
