# Generated by Django 5.1.7 on 2025-03-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='technology',
            name='unique_lower_technology_name',
        ),
    ]
