# Generated by Django 5.1.7 on 2025-03-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('react', 'React'), ('nextjs', 'Next.js'), ('vue', 'Vue.js'), ('angular', 'Angular'), ('nodejs', 'Node.js'), ('express', 'Express.js'), ('mongodb', 'MongoDB'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('firebase', 'Firebase'), ('aws', 'AWS'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('git', 'Git'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=50, unique=True),
        ),
    ]
