# Generated by Django 5.1.7 on 2025-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('programming', 'Programming'), ('web_dev', 'Web Development'), ('ai_ml', 'Artificial Intelligence & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('software', 'Software Engineering'), ('business', 'Business & Startups'), ('data_science', 'Data Science'), ('finance', 'Finance & Investment'), ('design', 'UI/UX & Product Design'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_app', 'Mobile App Development'), ('ai_ml', 'AI & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('data_science', 'Data Science'), ('game_dev', 'Game Development'), ('cloud', 'Cloud Computing'), ('devops', 'DevOps & Automation'), ('software', 'Software Engineering'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='portfolio.technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
